[package]
name = "lib-mikufans-proto"
version = "8.7.1"
edition = "2021"
rust-version = "1.70"

[dependencies]
# gRPC deps
prost = "0.13"
prost-types = "0.13"
tonic = "0.12"

[lints.clippy]
all = "allow"
