// This file is @generated by prost-build.
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MidStoryConfig {
    ///
    #[prost(message, optional, tag = "1")]
    pub gesture_type: ::core::option::Option<super::super::Int64Value>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoryConfig {
    ///
    #[prost(message, optional, tag = "1")]
    pub gesture_type: ::core::option::Option<super::super::Int64Value>,
}
