// This file is @generated by prost-build.
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PugvAnyModel {
    ///
    #[prost(int64, tag = "1")]
    pub season_id: i64,
    ///
    #[prost(int64, tag = "2")]
    pub episode_id: i64,
    ///
    #[prost(enumeration = "EpisodeStatus", tag = "3")]
    pub status: i32,
    ///
    #[prost(message, optional, tag = "4")]
    pub risk_control: ::core::option::Option<RiskControl>,
    ///
    #[prost(message, optional, tag = "5")]
    pub player_mask: ::core::option::Option<PlayerMask>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerMask {
    ///
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub prefix: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub suffix: ::prost::alloc::string::String,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskControl {
    ///
    #[prost(bool, tag = "1")]
    pub need_send_sms: bool,
    ///
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub risk_message: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub action_desc: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub send_sms_url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "6")]
    pub buvid: ::prost::alloc::string::String,
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EpisodeStatus {
    ///
    Unspecified = 0,
    ///
    TryWatchWhole = 1,
    ///
    NotTryWatch = 2,
    ///
    TryWatch5Minutes = 3,
}
impl EpisodeStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EpisodeStatus::Unspecified => "EPISODE_STATUS_UNSPECIFIED",
            EpisodeStatus::TryWatchWhole => "EPISODE_STATUS_TRY_WATCH_WHOLE",
            EpisodeStatus::NotTryWatch => "EPISODE_STATUS_NOT_TRY_WATCH",
            EpisodeStatus::TryWatch5Minutes => "EPISODE_STATUS_TRY_WATCH_5_MINUTES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EPISODE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EPISODE_STATUS_TRY_WATCH_WHOLE" => Some(Self::TryWatchWhole),
            "EPISODE_STATUS_NOT_TRY_WATCH" => Some(Self::NotTryWatch),
            "EPISODE_STATUS_TRY_WATCH_5_MINUTES" => Some(Self::TryWatch5Minutes),
            _ => None,
        }
    }
}
