// This file is @generated by prost-build.
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicAutoPlay {
    ///
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<super::super::Int64Value>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicDeviceConfig {
    ///
    #[prost(message, optional, tag = "1")]
    pub auto_play: ::core::option::Option<DynamicAutoPlay>,
}
