// This file is @generated by prost-build.
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FawkesReply {
    ///
    #[prost(string, tag = "1")]
    pub config: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub ff: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub dd: ::prost::alloc::string::String,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FawkesReq {
    ///
    #[prost(string, tag = "1")]
    pub appkey: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub env: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
}
