// This file is @generated by prost-build.
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArcContentPool {
    ///
    #[prost(message, repeated, tag = "1")]
    pub show_arcs: ::prost::alloc::vec::Vec<ArcInfo>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub backup_arcs: ::prost::alloc::vec::Vec<ArcInfo>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArcInfo {
    ///
    #[prost(message, optional, tag = "1")]
    pub rec_meta: ::core::option::Option<RecentRecommendMetaInfo>,
    ///
    #[prost(int64, tag = "2")]
    pub duration_sec: i64,
    ///
    #[prost(int64, tag = "3")]
    pub progress_sec: i64,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Badge {
    ///
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub text_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub text_color_night: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub bg_color: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub bg_color_night: ::prost::alloc::string::String,
    ///
    #[prost(enumeration = "BgStyle", tag = "6")]
    pub bg_style: i32,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FavContentPool {
    ///
    #[prost(message, repeated, tag = "1")]
    pub show_favs: ::prost::alloc::vec::Vec<FavInfo>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub backup_favs: ::prost::alloc::vec::Vec<FavInfo>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FavInfo {
    ///
    #[prost(message, optional, tag = "1")]
    pub rec_meta: ::core::option::Option<RecentRecommendMetaInfo>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HalfWatchedVideo {
    ///
    #[prost(message, optional, tag = "1")]
    pub module_info: ::core::option::Option<ModuleInfo>,
    ///
    #[prost(message, optional, tag = "2")]
    pub arc_content_pool: ::core::option::Option<ArcContentPool>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IconItem {
    ///
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "5")]
    pub red_dot: ::core::option::Option<RedDot>,
    ///
    #[prost(bool, tag = "6")]
    pub fixure: bool,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MineSelection {
    ///
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<IconItem>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MineSelectionContentReq {}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MineSelectionContentRes {
    ///
    #[prost(message, optional, tag = "1")]
    pub mine_selection: ::core::option::Option<MineSelection>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MineSelectionOptionItemsReq {}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MineSelectionOptionItemsRes {
    ///
    #[prost(message, repeated, tag = "1")]
    pub sections: ::prost::alloc::vec::Vec<SimpleMineSection>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MineSelectionOptionUpdateReq {
    ///
    #[prost(int64, repeated, tag = "1")]
    pub item_ids: ::prost::alloc::vec::Vec<i64>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MineSelectionOptionUpdateRes {}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleInfo {
    ///
    #[prost(message, optional, tag = "1")]
    pub more: ::core::option::Option<More>,
    ///
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "3")]
    pub pos: i64,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct More {
    ///
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub icon: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecentFav {
    ///
    #[prost(message, optional, tag = "1")]
    pub module_info: ::core::option::Option<ModuleInfo>,
    ///
    #[prost(message, optional, tag = "3")]
    pub fav_content_pool: ::core::option::Option<FavContentPool>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecentRecommendMetaInfo {
    ///
    #[prost(int64, tag = "1")]
    pub id: i64,
    ///
    #[prost(string, tag = "2")]
    pub cover: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "4")]
    pub add_time: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "5")]
    pub url: ::prost::alloc::string::String,
    ///
    #[prost(message, optional, tag = "6")]
    pub badge: ::core::option::Option<Badge>,
    ///
    #[prost(enumeration = "RecType", tag = "7")]
    pub rec_type: i32,
    ///
    #[prost(enumeration = "RecentRecReasonEnum", tag = "8")]
    pub rec_reason_enum: i32,
    ///
    #[prost(string, tag = "9")]
    pub sub_title: ::prost::alloc::string::String,
    ///
    #[prost(int64, tag = "10")]
    pub add_time_sec: i64,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RecentReq {
    ///
    #[prost(message, optional, tag = "1")]
    pub player_args: ::core::option::Option<
        super::super::archive::middleware::v1::PlayerArgs,
    >,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecentRes {
    ///
    #[prost(message, optional, tag = "1")]
    pub mine_selection: ::core::option::Option<MineSelection>,
    ///
    #[prost(message, optional, tag = "2")]
    pub recent_used: ::core::option::Option<RecentUsed>,
    ///
    #[prost(message, optional, tag = "3")]
    pub half_watched_videos: ::core::option::Option<HalfWatchedVideo>,
    ///
    #[prost(message, optional, tag = "4")]
    pub to_view: ::core::option::Option<ToView>,
    ///
    #[prost(message, optional, tag = "5")]
    pub recent_fav: ::core::option::Option<RecentFav>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecentUsed {
    ///
    #[prost(message, optional, tag = "1")]
    pub module_info: ::core::option::Option<ModuleInfo>,
    ///
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<IconItem>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RedDot {
    ///
    #[prost(bool, tag = "1")]
    pub show: bool,
    ///
    #[prost(int64, tag = "2")]
    pub num: i64,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveVideoReq {
    ///
    #[prost(enumeration = "ModuleType", tag = "1")]
    pub module_type: i32,
    ///
    #[prost(int64, tag = "2")]
    pub id: i64,
    ///
    #[prost(enumeration = "RecentRecReasonEnum", tag = "3")]
    pub rec_reason_enum: i32,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveVideoRes {}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SimpleMineSection {
    ///
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    ///
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<IconItem>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TabExtraInfo {
    ///
    #[prost(bool, tag = "1")]
    pub switch_to_mine_config_bubble: bool,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToView {
    ///
    #[prost(message, optional, tag = "1")]
    pub module_info: ::core::option::Option<ModuleInfo>,
    ///
    #[prost(message, optional, tag = "2")]
    pub arc_content_pool: ::core::option::Option<ArcContentPool>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopLeftTabReq {}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopLeftTabRes {
    ///
    #[prost(int32, repeated, tag = "1")]
    pub tabs: ::prost::alloc::vec::Vec<i32>,
    ///
    #[prost(enumeration = "Tab", tag = "2")]
    pub default_tab: i32,
    ///
    #[prost(message, optional, tag = "3")]
    pub extra: ::core::option::Option<TabExtraInfo>,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopLeftTabUpdateReq {
    ///
    #[prost(enumeration = "TopLeftGoto", tag = "1")]
    pub tab_goto: i32,
    ///
    #[prost(enumeration = "TabSelection", tag = "2")]
    pub tab_selection: i32,
    ///
    #[prost(enumeration = "TabUpdateSource", tag = "3")]
    pub source: i32,
}
///
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopLeftTabUpdateRes {}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BgStyle {
    ///
    Unknown = 0,
    ///
    Fill = 1,
    ///
    Stroke = 2,
    ///
    FillAndStroke = 3,
    ///
    NoFillAndNoStroke = 4,
}
impl BgStyle {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BgStyle::Unknown => "BG_STYLE_UNKNOWN",
            BgStyle::Fill => "BG_STYLE_FILL",
            BgStyle::Stroke => "BG_STYLE_STROKE",
            BgStyle::FillAndStroke => "BG_STYLE_FILL_AND_STROKE",
            BgStyle::NoFillAndNoStroke => "BG_STYLE_NO_FILL_AND_NO_STROKE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BG_STYLE_UNKNOWN" => Some(Self::Unknown),
            "BG_STYLE_FILL" => Some(Self::Fill),
            "BG_STYLE_STROKE" => Some(Self::Stroke),
            "BG_STYLE_FILL_AND_STROKE" => Some(Self::FillAndStroke),
            "BG_STYLE_NO_FILL_AND_NO_STROKE" => Some(Self::NoFillAndNoStroke),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModuleType {
    ///
    Unknown = 0,
    ///
    Toview = 1,
    ///
    RecentFav = 2,
    ///
    HalfWatchedVideo = 3,
}
impl ModuleType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ModuleType::Unknown => "MODULE_TYPE_UNKNOWN",
            ModuleType::Toview => "MODULE_TYPE_TOVIEW",
            ModuleType::RecentFav => "MODULE_TYPE_RECENT_FAV",
            ModuleType::HalfWatchedVideo => "MODULE_TYPE_HALF_WATCHED_VIDEO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODULE_TYPE_UNKNOWN" => Some(Self::Unknown),
            "MODULE_TYPE_TOVIEW" => Some(Self::Toview),
            "MODULE_TYPE_RECENT_FAV" => Some(Self::RecentFav),
            "MODULE_TYPE_HALF_WATCHED_VIDEO" => Some(Self::HalfWatchedVideo),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecType {
    ///
    Unknown = 0,
    ///
    Ugc = 1,
    ///
    Ogv = 2,
    ///
    Season = 3,
    ///
    FavFolder = 4,
}
impl RecType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RecType::Unknown => "REC_TYPE_UNKNOWN",
            RecType::Ugc => "REC_TYPE_UGC",
            RecType::Ogv => "REC_TYPE_OGV",
            RecType::Season => "REC_TYPE_SEASON",
            RecType::FavFolder => "REC_TYPE_FAV_FOLDER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REC_TYPE_UNKNOWN" => Some(Self::Unknown),
            "REC_TYPE_UGC" => Some(Self::Ugc),
            "REC_TYPE_OGV" => Some(Self::Ogv),
            "REC_TYPE_SEASON" => Some(Self::Season),
            "REC_TYPE_FAV_FOLDER" => Some(Self::FavFolder),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecentRecReasonEnum {
    ///
    RecentRecReasonUnknown = 0,
    ///
    RecentRecReasonToview = 1,
    /// @Deprecated
    RecentRecReasonHistory = 2,
    ///
    RecentRecReasonFavFolder = 21,
    ///
    RecentRecReasonFavDetail = 22,
    ///
    RecentRecReasonDeepWatchingHalf = 31,
    ///
    RecentRecReasonLookBackHalf = 32,
    ///
    RecentRecReasonLookBackMoreHalf = 33,
    ///
    RecentRecReasonLookBackMore = 34,
}
impl RecentRecReasonEnum {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RecentRecReasonEnum::RecentRecReasonUnknown => "RECENT_REC_REASON_UNKNOWN",
            RecentRecReasonEnum::RecentRecReasonToview => "RECENT_REC_REASON_TOVIEW",
            RecentRecReasonEnum::RecentRecReasonHistory => "RECENT_REC_REASON_HISTORY",
            RecentRecReasonEnum::RecentRecReasonFavFolder => {
                "RECENT_REC_REASON_FAV_FOLDER"
            }
            RecentRecReasonEnum::RecentRecReasonFavDetail => {
                "RECENT_REC_REASON_FAV_DETAIL"
            }
            RecentRecReasonEnum::RecentRecReasonDeepWatchingHalf => {
                "RECENT_REC_REASON_DEEP_WATCHING_HALF"
            }
            RecentRecReasonEnum::RecentRecReasonLookBackHalf => {
                "RECENT_REC_REASON_LOOK_BACK_HALF"
            }
            RecentRecReasonEnum::RecentRecReasonLookBackMoreHalf => {
                "RECENT_REC_REASON_LOOK_BACK_MORE_HALF"
            }
            RecentRecReasonEnum::RecentRecReasonLookBackMore => {
                "RECENT_REC_REASON_LOOK_BACK_MORE"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RECENT_REC_REASON_UNKNOWN" => Some(Self::RecentRecReasonUnknown),
            "RECENT_REC_REASON_TOVIEW" => Some(Self::RecentRecReasonToview),
            "RECENT_REC_REASON_HISTORY" => Some(Self::RecentRecReasonHistory),
            "RECENT_REC_REASON_FAV_FOLDER" => Some(Self::RecentRecReasonFavFolder),
            "RECENT_REC_REASON_FAV_DETAIL" => Some(Self::RecentRecReasonFavDetail),
            "RECENT_REC_REASON_DEEP_WATCHING_HALF" => {
                Some(Self::RecentRecReasonDeepWatchingHalf)
            }
            "RECENT_REC_REASON_LOOK_BACK_HALF" => Some(Self::RecentRecReasonLookBackHalf),
            "RECENT_REC_REASON_LOOK_BACK_MORE_HALF" => {
                Some(Self::RecentRecReasonLookBackMoreHalf)
            }
            "RECENT_REC_REASON_LOOK_BACK_MORE" => Some(Self::RecentRecReasonLookBackMore),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Tab {
    ///
    Unknown = 0,
    ///
    Listen = 1,
    ///
    Story = 2,
    ///
    Recent = 3,
}
impl Tab {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Tab::Unknown => "TAB_UNKNOWN",
            Tab::Listen => "TAB_LISTEN",
            Tab::Story => "TAB_STORY",
            Tab::Recent => "TAB_RECENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TAB_UNKNOWN" => Some(Self::Unknown),
            "TAB_LISTEN" => Some(Self::Listen),
            "TAB_STORY" => Some(Self::Story),
            "TAB_RECENT" => Some(Self::Recent),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TabSelection {
    ///
    TsUnknown = 0,
    ///
    TsOnlyListen = 1,
    ///
    TsOnlyStory = 2,
    ///
    TsOnlyRecent = 3,
    ///
    TsAll = 4,
}
impl TabSelection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TabSelection::TsUnknown => "TS_UNKNOWN",
            TabSelection::TsOnlyListen => "TS_ONLY_LISTEN",
            TabSelection::TsOnlyStory => "TS_ONLY_STORY",
            TabSelection::TsOnlyRecent => "TS_ONLY_RECENT",
            TabSelection::TsAll => "TS_ALL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TS_UNKNOWN" => Some(Self::TsUnknown),
            "TS_ONLY_LISTEN" => Some(Self::TsOnlyListen),
            "TS_ONLY_STORY" => Some(Self::TsOnlyStory),
            "TS_ONLY_RECENT" => Some(Self::TsOnlyRecent),
            "TS_ALL" => Some(Self::TsAll),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TabUpdateSource {
    ///
    SourceRecent = 0,
    ///
    SourceGame = 1,
}
impl TabUpdateSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TabUpdateSource::SourceRecent => "SOURCE_RECENT",
            TabUpdateSource::SourceGame => "SOURCE_GAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SOURCE_RECENT" => Some(Self::SourceRecent),
            "SOURCE_GAME" => Some(Self::SourceGame),
            _ => None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TopLeftGoto {
    ///
    GotoUnknown = 0,
    ///
    GotoMine = 1,
    ///
    GotoRecent = 2,
}
impl TopLeftGoto {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TopLeftGoto::GotoUnknown => "GOTO_UNKNOWN",
            TopLeftGoto::GotoMine => "GOTO_MINE",
            TopLeftGoto::GotoRecent => "GOTO_RECENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GOTO_UNKNOWN" => Some(Self::GotoUnknown),
            "GOTO_MINE" => Some(Self::GotoMine),
            "GOTO_RECENT" => Some(Self::GotoRecent),
            _ => None,
        }
    }
}
